theme = "hyde"
baseURL = "https://www.laurenfosgett.com"
languageCode = "en-us"
title = "Lauren Fosgett"


[params]
  AuthorName = "Lauren Fosgett"
  GitHubUser = "lfosgett"
  Subtitle = "IT Guru. Web Developer. Salesforce Enthusiast."