baseURL = "https://www.laurenfosgett.com/"
languageCode = "en-us"
title = "Lauren Fosgett"
theme = "purehugo"
Paginate = 10

[params]
  twitterName = "lfosgett"
  githubName = "lfosgett"
  linkedinName = "lfosgett"
  description = "IT Guru. Web Developer. Salesforce Enthusiast. \nCurrent Desert Dweller."